apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: prod
    project: devops-project
spec:
  project: devops-project

  source:
    repoURL: https://github.com/Govind-Kandale-1/devops-project
    targetRevision: main
    path: kubernetes/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
  # No automated sync — triggered manually via CI after approval gate

  revisionHistoryLimit: 10
